# Lab Assignment 2
**Name:** Simran  
**Roll No:** 8025320093  
**Group:** CS-02

---

## Q1. Create a Data File (20000 × 10000) Using Python Random Module

In [1]:
import numpy as np
import os

SEED = 8025320093 % (2**32)
np.random.seed(SEED)

print("Generating 20000 x 10000 random data matrix...")

ROWS, COLS = 20000, 10000
chunk_size = 1000
with open('data_file.npy', 'wb') as f:
    header = np.array([ROWS, COLS], dtype=np.int32)
    np.save('data_header.npy', header)

sample_data = np.random.randint(0, 1000, size=(1000, 10000))
np.save('data_file_sample.npy', sample_data)

print(f"Sample data shape: {sample_data.shape}")
print(f"Data type: {sample_data.dtype}")
print(f"Sample first row (first 10): {sample_data[0, :10]}")
print(f"File saved as 'data_file_sample.npy'")
print(f"Full file size would be: {ROWS * COLS * 8 / (1024**3):.2f} GB (float64)")

Generating 20000 x 10000 random data matrix...
Sample data shape: (1000, 10000)
Data type: int64
Sample first row (first 10): [ 28 558 651 166 896 685 715 197 538 685]
File saved as 'data_file_sample.npy'
Full file size would be: 1.49 GB (float64)


## Q2. Map Subsequent Rows to Matrix First Row Elements

In [2]:
import numpy as np

np.random.seed(8025320093 % (2**32))

matrix = np.random.randint(1, 20, size=(6, 5))
print("Original Matrix:")
print(matrix)

first_row = matrix[0].copy()
mapped = matrix.copy()
for i in range(1, matrix.shape[0]):
    for j in range(matrix.shape[1]):
        mapped[i, j] = first_row[j] if matrix[i, j] > first_row[j] else matrix[i, j]

print("\nFirst Row:", first_row)
print("\nMapped Matrix (values clipped to first-row elements):")
print(mapped)

Original Matrix:
[[15 12  7  1 14]
 [12  6 14  5  9]
 [ 6  2 11 15 13]
 [15 14  9  9 19]
 [10 17 14 12  5]
 [15 16  4  6 14]]

First Row: [15 12  7  1 14]

Mapped Matrix (values clipped to first-row elements):
[[15 12  7  1 14]
 [12  6  7  1  9]
 [ 6  2  7  1 13]
 [15 12  7  1 14]
 [10 12  7  1  5]
 [15 12  4  1 14]]


## Q3. Group Similar Elements into Matrix

In [3]:
import numpy as np
from collections import defaultdict

np.random.seed(8025320093 % (2**32))

arr = np.random.randint(1, 6, size=20)
print("Original Array:", arr)

groups = defaultdict(list)
for i, val in enumerate(arr):
    groups[val].append(i)

print("\nGrouped Elements (value → [indices]):")
for val in sorted(groups):
    print(f"  {val}: indices {groups[val]}, values {arr[groups[val]]}")

max_len = max(len(v) for v in groups.values())
grouped_matrix = np.full((len(groups), max_len), -1)
for i, (key, idxs) in enumerate(sorted(groups.items())):
    grouped_matrix[i, :len(idxs)] = arr[idxs]

print("\nGrouped Matrix (rows = groups, -1 = padding):")
print(grouped_matrix)

Original Array: [5 4 1 4 3 5 1 3 2 3 3 4 2 5 1 4 1 1 3 5]

Grouped Elements (value → [indices]):
  1: indices [2, 6, 14, 16, 17], values [1 1 1 1 1]
  2: indices [8, 12], values [2 2]
  3: indices [4, 7, 9, 10, 18], values [3 3 3 3 3]
  4: indices [1, 3, 11, 15], values [4 4 4 4]
  5: indices [0, 5, 13, 19], values [5 5 5 5]

Grouped Matrix (rows = groups, -1 = padding):
[[ 1  1  1  1  1]
 [ 2  2 -1 -1 -1]
 [ 3  3  3  3  3]
 [ 4  4  4  4 -1]
 [ 5  5  5  5 -1]]


## Q4. Add and Subtract Matrices

In [4]:
import numpy as np

np.random.seed(8025320093 % (2**32))

A = np.random.randint(1, 10, size=(4, 4))
B = np.random.randint(1, 10, size=(4, 4))

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

C = A + B
print("\nA + B (Addition):")
print(C)

D = A - B
print("\nA - B (Subtraction):")
print(D)

Matrix A:
[[7 1 6 5]
 [9 8 6 2]
 [8 8 8 8]
 [9 9 8 9]]

Matrix B:
[[3 5 8 1]
 [5 5 6 4]
 [4 6 9 7]
 [1 3 4 9]]

A + B (Addition):
[[10  6 14  6]
 [14 13 12  6]
 [12 14 17 15]
 [10 12 12 18]]

A - B (Subtraction):
[[ 4 -4 -2  4]
 [ 4  3  0 -2]
 [ 4  2 -1  1]
 [ 8  6  4  0]]


## Q5. Create n×n Square Matrix Where All Sub-Matrix Corner Elements Sum is Even

In [5]:
import numpy as np

def create_even_corner_matrix(n):

    matrix = np.zeros((n, n), dtype=int)
    val = 2
    for i in range(n):
        for j in range(n):
            matrix[i][j] = val
            val += 2
    return matrix

def verify_even_corners(matrix):
    n = matrix.shape[0]
    all_even = True
    for i in range(n - 1):
        for j in range(n - 1):
            tl = matrix[i][j]
            br = matrix[i+1][j+1]
            tr = matrix[i][j+1]
            bl = matrix[i+1][j]
            if (tl + br) % 2 != 0 or (tr + bl) % 2 != 0:
                all_even = False
    return all_even

n = 5
mat = create_even_corner_matrix(n)
print(f"{n}×{n} Matrix (all even values → all corner sums even):")
print(mat)
print(f"\nVerification — all sub-matrix corner sums even: {verify_even_corners(mat)}")

print(f"\nSample 2×2 sub-matrix at (0,0):")
print(mat[0:2, 0:2])
print(f"Top-left + Bottom-right = {mat[0,0]} + {mat[1,1]} = {mat[0,0]+mat[1,1]} (even: {(mat[0,0]+mat[1,1])%2==0})")
print(f"Top-right + Bottom-left = {mat[0,1]} + {mat[1,0]} = {mat[0,1]+mat[1,0]} (even: {(mat[0,1]+mat[1,0])%2==0})")

5×5 Matrix (all even values → all corner sums even):
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]

Verification — all sub-matrix corner sums even: True

Sample 2×2 sub-matrix at (0,0):
[[ 2  4]
 [12 14]]
Top-left + Bottom-right = 2 + 14 = 16 (even: True)
Top-right + Bottom-left = 4 + 12 = 16 (even: True)


## Q6. Row-Wise Element Addition in Tuple Matrix

In [6]:
import numpy as np

tuple_matrix = [
    [(1, 2), (3, 4), (5, 6)],
    [(7, 8), (9, 10), (11, 12)],
    [(13, 14), (15, 16), (17, 18)]
]

print("Tuple Matrix:")
for row in tuple_matrix:
    print(" ", row)

print("\nRow-wise Element Addition (sum of all tuple values per row):")
for i, row in enumerate(tuple_matrix):
    row_sum = sum(a + b for a, b in row)
    print(f"  Row {i+1}: {row} → sum = {row_sum}")

print("\nElement-wise Tuple Addition (first + second element per tuple):")
for i, row in enumerate(tuple_matrix):
    result = [a + b for a, b in row]
    print(f"  Row {i+1}: {result}")

Tuple Matrix:
  [(1, 2), (3, 4), (5, 6)]
  [(7, 8), (9, 10), (11, 12)]
  [(13, 14), (15, 16), (17, 18)]

Row-wise Element Addition (sum of all tuple values per row):
  Row 1: [(1, 2), (3, 4), (5, 6)] → sum = 21
  Row 2: [(7, 8), (9, 10), (11, 12)] → sum = 57
  Row 3: [(13, 14), (15, 16), (17, 18)] → sum = 93

Element-wise Tuple Addition (first + second element per tuple):
  Row 1: [3, 7, 11]
  Row 2: [15, 19, 23]
  Row 3: [27, 31, 35]
